# Site settings
title: Prateek Sahay
email: ptkinvent@gmail.com
description: >- # Ignore newlines
  Welcome to the personal website of Prateek Sahay. I'm a robotics software
  engineer working at the Advanced Technologies Group at Uber in Pittsburgh, PA.
  I use this website to display my past projects and write up some of my
  thoughts.
permalink: /blog/:categories/:title:output_ext
url: "https://prateeksahay.com"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Sass
sass:
  sass_dir: _scss
  style: compressed # Will take any native Sass options

# Collections
collections:
  projects:
    output: true
